#!/bin/bash

# XIL: XBPS Interpeter Layer: Utility that makes basic XBPS commands more sane
# Copyright (c) James Gillman [jronaldgillman@gmail.com], gitlab: @safetypanda
# See https://github.com/void-linux for more info on Void Linux & XBPS

# Released under the GNU General Public License version 3+
# Refer to LICENSE file for license information.

version="1.0"

version() 
{
  echo "*----------------------------------------------------------------*"
  echo " XIL: XBPS Interpeter Layer Version $version"
  echo " James Gillman [jronaldgillman@gmail.com] gitlab: @safetypanda"
  echo ""
  echo " Current XBPS version: $(xbps-query -v --version)"   
  echo ""
  echo " XIL Copyright (C) 2019  James Gillman"
  echo " This program comes with ABSOLUTELY NO WARRANTY;"
  echo " This is free software, and you are welcome to redistribute it "
  echo " under certain conditions. Refer to included GNU License!"
  echo "*----------------------------------------------------------------*"
  echo ""
}

usage()
{
  echo ""
  echo "usage: xil [OPTIONS] [<ARGUMENTS>]"
  echo ""
  echo "Options:"
  echo "update            -> Update Repos"
  echo "upgrade           -> Upgrade System"
  echo "listrepos         -> Lists all configured Repos"
  echo "addrepo <ARGS>    -> Adds a Repository"
  echo "search <NAME>     -> Searches for packages using a name"
  echo "install <PKG(s)>  -> Installs package(s)"
  echo "remove <PKG(s)>   -> Removes package(s)"
  echo "recursiveremove   -> Removes package(s) and it's dependencies"
  echo "autoremove        -> Removes orphaned packages"
  echo "help              -> Shows this dialog"
  echo "details           -> Shows version, contact and license info"
 echo ""
}

privCheck () 
{
  if [[ "$EUID" -gt 0 ]]; then
    echo "ERROR: This operation requires escalated privileges. Exiting!"
    exit 1
  fi
}

arg="$1"

if [ -z $arg ]
then
  echo "ERROR: Options missing, try --help."
  echo "usage: xil [OPTIONS] [<ARGUMENTS>]"
  exit 2
fi
	
case "$arg" in
  update)
    shift
    privCheck
    echo ""
    xbps-install -S
  ;;

  help|--help)
    usage
  ;;

  upgrade)
    shift
    privCheck
    echo ""
    xbps-install -Suv
  ;;
  
  listrepos)
    echo ""
    xbps-query -v -L
  ;;

  addrepo)
    shift
    privCheck
    while [ "$#" -gt 0 ]; do
    echo ""
    xbps-install "$1"
    done
  ;;

  search)
    shift
    echo ""
    xbps-query -Rs "$@"
  ;;
    
  install)
    shift
    privCheck
    if [ "$#" -lt 1 ]; then
      echo "ERROR: Argument missing, try --help."
      exit 1
    fi
    xbps-install -S "$@"
    ;;

  remove)
    shift
    privCheck
    if [ "$#" -lt 1 ]; then
      echo "ERROR: Argument missing, try --help."
      exit 1
    fi
    echo ""
    xbps-remove "$@"
    ;;

  recursiveremove)
    shift
    privCheck
    if [ "$#" -lt 1 ]; then
      echo "ERROR: argument missing, try --help."
      exit 1
    fi
    xbps-remove -R "$@"
  ;;

  autoremove)
    shift
    privCheck
    xbps-remove -O
    ;;

  details)
    version
    ;;

  *)
   echo "ERROR: Not a valid command, try --help"
   exit 1
   ;;

esac

exit 0